### ISSUE TITLE
OpenMLDB v0.5 Roadmap

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#1506]
This is the roadmap for the OpenMLDB v0.5 release. As a community-driven project, we love your feedback. Please follow this thread to join our discussion:
- You may ask us about the detail of features on this roadmap.
- You are welcome to contribute to any items (even they are not on the list).
- Please reply this topic if you are planning to implement any features that are not on the list, and we will add them here gradually.

## Release Date (Tentative)
v0.5.0: 25th Apr 2022

## Online Core Engine
- [x] Pre-aggregation optimization for performance enhancement
- [x] The new RocksDB based storage engine

## Offline Core Engine
- [x] The new blocking APIs to execute offline queries
- [x] Performance enhancement 

## CLI and SQL
- [x] Support long timestamp type for csv import
- [x] The new SQL syntax `CREATE DATABASE IF NOT EXISTS`
- [x] Supporting blocking execution for async SQLs in CLI
- [x] Supporting `show jobs` with a specific order
- [x] Supporting offline queries to display results instead of job info only
- [x] Supporting C UDF
- [x] Supporting to set global system variable
- [ ] Supporting feature encoding: one-hot and label encoding
- [ ] Supporting SQL deployment for non-empty tables
- [x] Supporting blocking execution for offline jobs in CLI, and showing returned results in CLI as well
- [x] Long window aggregator support based on the pre-aggregation optimization: `sum`, `count`, `min`, `max`, `avg` ([OpenMLDB RFC-010 : Long Time Window](https://docs.google.com/document/d/18dX75IxqyvH39Lu9PEcRTMG2-FMS_bPw0pYsLmmzSXU/edit?usp=sharing))

## Java SDK
- [x] The new API `SqlClusterExecutor::executeSQL(sql)`
- [x] Supporting blocking execution for async SQLs
- [x] Supporting the standalone version

## Python SDK
- [x] The new API `openmldb.dbapi.connect().cursor().executemany()`: batch insertion
- [x] The new API `openmldb.dbapi.connect().cursor().batch_row_request()`: executing batch requests
- [x] The new API `openmldb.dbapi.connect().cursor().in_online_mode()`: checking whether in the online mode
- [x] The new API `openmldb.dbapi.connect().cursor().get_tables(db)`: getting all tables of a given database
- [x] The new API `openmldb.dbapi.connect().cursor().get_all_tables()`: getting all tables of all databases
- [x] The new API `openmldb.dbapi.connect().cursor().get_databases()`: getting all databases
- [x] The new API `openmldb.dbapi.connect().cursor().executeRequest(SQL, parameter)`: executing a request
- [x] The new API `openmldb.dbapi.connect().cursor().get_resultset_schema()`: getting the schema of the result set
- [x] Supporting blocking execution for async SQLs
- [x] Supporting the standalone version

## Monitoring
- [x] Enhancement for the online monitoring ([OpenMLDB RFC-011 : Online Monitoring](https://docs.google.com/document/d/1O-JL-slBneDnpVuR3_FORQ6kPGdfwn7QmdmSTxv2eXo/edit?usp=sharing))

## Ecosystem
- [ ] [Online data sources] Apache Kafka connector
- [x] [Online data sources] Apache Pulsar connector
- [ ] [Deployment] Airflow provider package

## Usability
- [x] Migrating the Chinese documentation server to https://openmldb.ai/docs/zh 
- [x] English documentation translation and be accessible at: https://openmldb.ai/docs/en
- [ ] Performance benchmarking for online queries
- [ ] Building the use case of OpenMLDB + XGBoost
- [ ] Building the use case of OpenMLDB + Kafka 
- [x] Building the use case of OpenMLDB + Pulsar
- [ ] Building the use case of OpenMLDB + Airflow

**Comment by Shouren** [comment]
Hi,
Any details of the feature of  "Supporting C UDF" in the section of "CLI and SQL" ? Does it support dynamic loading?

**Comment by lumianph** [comment]
> Hi, Any details of the feature of "Supporting C UDF" in the section of "CLI and SQL" ? Does it support dynamic loading?

C UDF should be able to support dynamic loading. This feature is almost done. @dl239 may show some examples later.

**Comment by lumianph** [comment]
We are very pleased to announce that we have released our v0.5.0.

### Highlights

- We have introduced an important performance optimization technique of pre-aggregation, which can significantly improve the performance for a query with time windows containing massive amount of rows, e.g., a few millions. (#1532 #1573 #1583 #1622 #1627 #1672 # 1712 @zhanghaohit @nautaa)
- We have added a new storage engine that supports persistent storage (such as HDD and SSD) for the online SQL engine. Such a storage engine is helpful when a user wants to reduce the cost with acceptable performance degradation. (#1483 @Leowner)
- We have supported C/C++ based User-Defined Functions (UDFs) with dynamic registration to enhance the development experience.  (#1509 #1733 #1700 @dl239 @tobegit3hub)

### Other Features

- Enhance the OpenMLDB Prometheus exporter ( #1584, #1645, #1754 @aceforeverd )
- Support collecting statistics of query response time for online queries ( #1497, #1521 @aceforeverd )
- Support new SQL commands: `SHOW COMPONENTS`, `SHOW TABLE STATUS` (#1380 #1431 #1704 @aceforeverd)
- Support setting global variables (#1310 #1359 #1364 @keyu813 @aceforeverd)
- Support reading Spark configuration files from the CLI (#1600 @tobegit3hub)
- Support using multiple threads for the Spark local mode (#1675 @tobegit3hub)
- Enhance the performance of join by using the Spark's native expression (#1502 tobegit3hub)
- Support the validation for TaskManager configuration (#1262 @tobegit3hub)
- Support tracking unfinished jobs in the TaskManager (#1474 @tobegit3hub)
- Other minor features (#1601 @dl239; #1574 @vagetablechicken; #1546 @keyu813; #1729 @vagetablechicken; #1460 @tobegit3hub)

### Bug Fixes
- Incorrect results when the order of conditions specified in `where` is different from that of the index (#1709 @aceforeverd)
- Incorrect results of `lag`/`at`/`lead` under certain circumstances (#1605 #1739 @aceforeverd)
- Memory leakage in `zk_client` (#1660 @wuxiaobai24)
- Catalog update failed if the role of a tablet is changed (#1655 @dl239)
- Related bugs about `UnsafeRow` for the offline engine (#1298, #1312, #1326, #1362, #1637, #1381, #1731 @tobegit3hub)
- Incorrect results after adding a new index in the standalone mode (#1721 @keyu813)
- Incorrect results of `SHOW JOBS` under certain circumstances (#1453 @tobegit3hub)
- Incorrect results of the date columns with `UnsafeRowOpt`(#1469 @tobegit3hub)
- Other minor bug fixes (#1698 @kfiring; #1651 @kutlayacar; #1621 @KaidoWang; #1150, #1243 @tobegit3hub; )

### Code Refactoring
#1616 @dl239; #1743 @zjx1319

### Acknowledgement
We appreciate the contribution to this release from all of our contributors, especially those from the community, including @nautaa @Leowner @keyu813 @wuxiaobai24 @kfiring @kutlayacar @KaidoWang @zjx1319 

We are looking forward to your contribution!
