### ISSUE TITLE
OpenMLDB v0.6 Roadmap

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#1519]
We are collecting requirements for the OpenMLDB v0.6. This version is aiming at the stability and usability enhancement. Meanwhile it will be particularly focusing on issues raised from the community. 

- If you have any suggestions for new features, please reply this thread to join our discussion.
- If you are interested in implementing any items (even they are not on the below list), please also reply this thread. We will guide you to create an issue to discuss in detail. 

## Release Date (Tentative)
v1.0.0: 30th Jun 2022

## Core
- [x] Enhancing the long window option to support more queries, such as those with suffix `_where`, `_cate`, `_cate_where`
- [ ] Integration with feature encoding algorithms, such as one-hot, label encoder, and so on
- [ ] Supporting deployment with existing data
- [x] Supporting the new syntax of `EXCLUDE CURRENT ROW`

## SQL and CLI
- [x] The new aggregate function `percentile`
- [x] The new aggregate function `median`
- [x] The new aggregate function `mean`
- [x] The new aggregate function `std`

## Ecosystem
- [x] [Deployment] Integration with Airflow
- [x] [Deployment] Integration with DolphinScheduler
- [ ] [Data sources] Integration with Flink

## Usability
- [ ] Adding a debug tracing tool
- [x] Adding a troubleshooting tool for the database
- [ ] Adding a performance profiling tool
- [ ] Supporting the deployment that consists of multiple queries
- [ ] Supporting to output encoded features as standard formats (such as CSV and LIBSVM) that can be directly fed into popular machine learning frameworks
- [x] The complete English documentation
