### ISSUE TITLE
Collect v0.4.4 features

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1530]
Features
- #1231 @dl239  29 days ago
- #1302 @tobegit3hub   2.24
- #1402 @hezhaozhao-git 14 days ago
- #1325 @HuilinWu2  
- #1486 @vagetablechicken 7 days ago
- #1511 @vagetablechicken   
- #1485 @keyu813

Bugfix
- #1415 @dl239 19 days ago
- #1440 @vagetablechicken 12 days ago
- #1540 @dl239 
- #1443 @jingchen2222 14 days ago
- #1511 @vagetablechicken   

Code Refactoring  
- #1467 @dl239 12 days ago
- #1513 @dl239  
- #1503 @dl239

**Comment by aceforeverd** [comment]
all fine

**Comment by lumianph** [comment]
we should at least have the feature of SDK support of the standalone version

**Comment by lumianph** [comment]
Please help confirm the documentations are also ready for the following features.

Features
- [x] #1231 @dl239  29 days ago
- [x] #1302 @tobegit3hub   2.24
- [ ] #1402 @hezhaozhao-git 14 days ago
- [x] #1325 @HuilinWu2  
- [x] #1486 @vagetablechicken 7 days ago
- [x] #1511 @vagetablechicken   
- [x] #1485 @keyu813

**Comment by lumianph** [comment]
### Features
- Support the standalone version by Java and Python SDKs (#1302 #1325 #1485 @tobegit3hub @HuilinWu2 @keyu813)
- Support the blocking execution for offline queries (#1486 @vagetablechicken )
- Add the `getStatement` API in Java SDK (#1231 @dl239 )
- Support multiple rows insertion in the Python SDK (#1402 @hezhaozhao-git )
- Support the JDBC connection (#1511 @vagetablechicken )

### Bug Fixes
- The error message is empty when executing `show deployment` in CLI fails. (#1415 @dl239 )
- The `show job` and `show jobs` cannot display correct information. (#1440 @vagetablechicken )
- The built-in function execution on a string filed with the length of greater than 2048 characters causes OpenMLDB crash. (#1540 @dl239 )
- The simple expression inference fails in some cases (#1443 @jingchen2222 )
- The `PreparedStatement` in Java SDK does not perform as expected.  (#1511 @vagetablechicken )

### Code Refactoring
#1467 @aimanfatima ; #1513 @L-Y-L ; #1503 @Stevinson ;

### Acknowledgement
We appreciate the contribution to this release from all of our contributors, especially those from the community who are not from 4Paradigm's core OpenMLDB team, including @hezhaozhao-git @HuilinWu2 @keyu813 @aimanfatima @L-Y-L @Stevinson . We are looking forward to your contribution!

**Comment by lumianph** [comment]
@dl239 remember to add the acknowledgement in the release note

**Comment by lumianph** [comment]
@vagetablechicken  the doc for `executemany` is still missing?

**Comment by dl239** [comment]
> @dl239 remember to add the acknowledgement in the release note

ok
