### ISSUE TITLE
OpenMLDB v0.7 Roadmap

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#2547]
We are collecting requirements for the OpenMLDB v0.7. This version is particularly to improve the SQL functionality and system usability. It will also solve issues raised from the community. Furthermore, we are also going to integrate a few very interesting features that are contributed by our community in this version. We really appreciate our community developers! 

If you have any suggestions for new features, please reply to this thread to join our discussion.
If you are interested in implementing any items (even they are not on the below list), please also reply to this thread. We will guide you to create an issue to discuss in detail.

# Release Date
Jan 2023

# Online Engine
- [x] Support batch processing under the online mode
- [x] Decouple the TaskManager from the online mode
- [x] Support to limit the memory usage, to prevent the process killed by the OS when memory consumption exceeding the physical limit

# SQL Functionality
- [x] Add new syntax checking APIs, to validate SQLs before execution and deployment
- [x] Support aggregation over a full table (#2499)
- [x] Support `top_n_value_*_cate_where` (#2502)
- [ ] Support feature encoding
- [ ] Support subqueries with simple project
- [ ] Support `list`
- [ ] Support lambda functions
- [ ] Support `eliminatechar`
- [ ] Support `round`
- [ ] Support `if-not-enough`
- [ ] Support `first_of_window` and `first`
- [ ] Support `is_in_window`
- [x] Support `datediff`
- [x] #1807 

# High Availability
- [x] Enhance the ability of recovery when any of the components are down

# Usability
- [x] Improve the maintenance tool, to reduce the complexity of maintenance, such as upgrade, recovery, and scale-out
- [x] Improve the output logs
- [ ] Support deployment with data (#1203)
- [ ] Open-source the tool for online-offline consistency verification, which previously is an internal tool
- [ ] Improve the system status monitoring tools, simplify the usage and centralize the information

# Tools and SDKs
- [x] Add a data export tool (contributed by @xiaopanz)
- [x] Add a Golang SDK (contributed by @qsliu2017)
- [x] Add a C++ SDK (contributed by @Json-L)
- [x] Add an auto feature generation tool (contributed by @explcre)

# Deployment
- [ ] Support SUSE LES 12 SP3/SP5, CentOS 8, Kylin V10
- [x] Support cloud deployment on Alibaba Cloud
- [x] The offline engine supports Yarn 3.2 and 3.1.1

# Ecosystem
- [x] Add a connector to allow the offline engine to read data from Apache Hive

# Docs and Blogs
- [x] Detailed description of OpenMLDB supported SQL syntax, especially about limitation and requirements 
- [x] Performance report of the disk-based storage engine
- [ ] Introduction and report about multi-cluster deployment
- [ ] Introduction of two application modes based on OpenMLDB, decision-making during and after the process
- [x] Improve the document structure

# Bug Fixes
Please refer to the [issues with the label of `bug` and milestone of `v0.7`](https://github.com/4paradigm/OpenMLDB/issues?q=is%3Aissue+label%3Abug+milestone%3Av0.7+)

**Comment by ChenpiDog** [comment]
#2608 It is expected that OpenMLDB has both **Data Warehouse** and **Data Analysis** functions: **OLAP** can be enhanced, such as **real-time ETL**, where users can achieve **real-time ETL** by writing **SQL**.
