### ISSUE TITLE
Add OpenMLDB docs

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/OpenMLDB#352]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Resolved by https://github.com/4paradigm/openmldb-docs-zh/issues/5
**Describe alternatives you've considered**

**Additional context**

**Comment by jingchen2222** [comment]
### TODO

- [x] add docs directory
- [x] reorganize docs summary
- [ ] auto deploy docs

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [docs reorganize, review and udpate](https://trello.com/c/EW0F7yOb/1-docs-reorganize-review-and-udpate)

**Comment by aceforeverd** [comment]
this issue can be closed ? @jingchen2222

**Comment by jingchen2222** [comment]
Sure.
