### ISSUE TITLE
Eliminate the concept of performance-sensitive mode for users

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#796]
The performance-sensitive mode introduces additional learning cost for users. We may consider to hide this concept for users. Intuitively, if the index is not built, it is acceptable that the performance slows down. The users only need to be aware of the index building, but not another concept of performance-sensitive mode.

**Comment by jingchen2222** [comment]
Exactly.
The performance-sensitive mode is enabled only for online serving. Otherwise, the db will run in performance-insensitive mode.

**Comment by jingchen2222** [comment]
We had better eliminate this concept in version 0.4.0.
```bash
> USE demo_db;
# execute with performance-sensitive=false
> SELECT pk1, pk2, sum(col1) over w1, sum(col2) OVER w2 FROM t1 WINDOW AS 
w1(PARTITION BY pk1 ORDER BY std_date ROWS_RANGE 1d PRECEDING AND CURRENT ROW),
w2(PARTITION BY pk2 ORDER BY std_date ROWS_RANGE 1d PRECEDING AND CURRENT ROW);

# deploy SQL with  performance-sensitive=true
> DEPLOY IF NOT EXISTS demo_deploy1 SELECT pk1, pk2, sum(col1) over w1, sum(col2) OVER w2 FROM t1 WINDOW AS 
w1(PARTITION BY pk1 ORDER BY std_date ROWS_RANGE 1d PRECEDING AND CURRENT ROW),
w2(PARTITION BY pk2 ORDER BY std_date ROWS_RANGE 1d PRECEDING AND CURRENT ROW);
```

**Comment by lumianph** [comment]
If we want to do this in v040, we may look at the workload and schedule, let's discuss the detail offline.

**Comment by jingchen2222** [comment]
**Is your feature request related to a problem? Please describe.**

The performance-sensitive mode introduces additional learning cost for users. We may consider to hide this concept for users. Intuitively, if the index is not built, it is acceptable that the performance slows down. The users only need to be aware of the index building, but not another concept of performance-sensitive mode.

**Describe the solution you'd like**

### Time estimate
  - develop: 5d
  - testing: 2d @wuyou10206 (remove unnecessary test for performance sensitive)
### ToDo
- [ ] remove `performance_sensitive` setting from `SetVariable() {...}` in src/cmd/sql_cmd.h
- [ ] remove `SQLClusterRouter::performance_sensitive_`
- [ ] remove performance_sensitive configure from Engine: 
- [ ] change YAML case mode from performance-sensitive to request
- [ ] turn-off cli batch queries test under performance-sensitive mode @wuyou10206 
- [ ] remove set performance sensitive configure in quick start or other documents

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by jingchen2222** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Eliminate the concept of performance-sensitive mode for users](https://trello.com/c/kISPjYBa/31-eliminate-the-concept-of-performance-sensitive-mode-for-users)
